# Generated by Django 5.1.15 on 2026-04-12 18:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailytask",
            name="date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
