import re
import joblib
import os

BASE_DIR = os.path.dirname(__file__)

# Load model
model = joblib.load(os.path.join(BASE_DIR, "model.pkl"))
vectorizer = joblib.load(os.path.join(BASE_DIR, "vectorizer.pkl"))


# 🔹 Extract amount (handles ₹, commas, decimals)
def extract_amount(text):
    match = re.search(r'(\d+(?:,\d+)*(?:\.\d+)?)', text)
    if match:
        return float(match.group().replace(",", ""))
    return None


def parse_voice_text(text):
    text_lower = text.lower()

    # 🔹 Amount
    amount = extract_amount(text_lower)

    # 🔹 ML prediction
    X = vectorizer.transform([text_lower])
    category = model.predict(X)[0]

    try:
        confidence = max(model.predict_proba(X)[0])
    except:
        confidence = 1.0

    # Load dynamic mapping generated by train_model.py
    import json
    try:
        with open(os.path.join(BASE_DIR, "category_mapping.json"), "r") as f:
            mapping = json.load(f)
    except FileNotFoundError:
        mapping = {}

    # 🔹 Transaction type dynamically resolved
    transaction_type = mapping.get(category, "EXPENSE")

    return {
        "amount": amount,
        "category": category,
        "transaction_type": transaction_type,
        "confidence": round(confidence, 2),
        "description": text
    }